import type { Language } from "../types.js";

export const ui = {
  zh: {
    brandSubtitle: "个人记忆库",
    workspace: "工作区",
    collections: "集合",
    connect: "连接",
    navAll: "全部记忆",
    navTimeline: "时间线",
    navPreferences: "偏好与习惯",
    navScopes: "Scope 分类",
    navTags: "标签",
    navMcp: "MCP 服务",
    navSettings: "设置",
    localStorage: "本地存储",
    memories: "MEMORIES",
    scopes: "SCOPES",
    scopesNote: "分类数量",
    lastSync: "LAST SYNC",
    justNow: "刚刚",
    localDatabase: "本地数据库",
    localOnly: "完全本地",
    localOnlyDesc: "你的记忆只留在这台设备",
    newMemory: "新建记忆",
    search: "搜索记忆...",
    allScopes: "所有 Scope",
    reading: "读取中...",
    countSuffix: "条记忆",
    sortRecent: "按最近更新排序",
    sortTimeline: "按发生时间排序",
    sortGrouped: "按 Scope 分组",
    globalMemory: "全局记忆",
    emptyMatch: "这里还没有匹配的记忆",
    emptyHelp: "试试换一个关键词或调整筛选条件。",
    loadFailed: "记忆读取失败",
    retry: "重试",
    noTags: "暂无标签",
    settingsManaged: "设置已由本地配置管理",
    detailEyebrow: "记忆详情",
    close: "关闭",
    detailEmpty: "选择一条记忆",
    detailEmptyDesc: "查看完整内容、来源和元数据",
    confidence: "置信度",
    created: "创建时间",
    updated: "最后更新",
    source: "来源",
    agentWritten: "Agent 写入",
    scope: "Scope",
    signals: "信号",
    importance: "重要性",
    recallCount: "召回次数",
    times: "次",
    original: "查看原始记录",
    switchLanguage: "切换到 English",
    newMemoryEyebrow: "新建记忆",
    composerTitle: "保存一条记忆",
    content: "记忆内容",
    contentPlaceholder: "例如：用户偏好使用简洁的工具界面。",
    type: "类型",
    scopeOptional: "可选，例如：/path/to/project",
    sourcePlaceholder: "例如：Claude Code / 手动添加",
    writeLocal: "写入本地 SQLite",
    preferenceRecall: "召回方式",
    persistentPreference: "常驻偏好",
    conditionalPreference: "条件偏好",
    persistentPreferenceHint: "每次任务开始时固定返回",
    cancel: "取消",
    save: "保存记忆",
    languageCode: "EN",
    timelineItems: "条",
    languageName: "中文",
    languageTitle: "界面语言",
    languageDescription: "选择工作台使用的语言。",
    languageZh: "中文",
    languageEn: "English",
    languageSaved: "语言已更新",
    languageSaveFailed: "语言更新失败，请稍后重试。",
    backupEyebrow: "数据备份",
    backupTitle: "导出与导入",
    backupDescription: "导出记忆与安全配置，或从 JSON 备份恢复。替换模式会覆盖当前记忆。",
    exportBackup: "导出 JSON",
    importMerge: "合并导入",
    importReplace: "替换导入",
    replaceConfirm: "替换导入会删除当前所有记忆，并使用备份内容替代。确定继续吗？",
    backupImported: (imported: number, skipped: number) => `导入 ${imported} 条记忆，跳过 ${skipped} 条。`,
    backupFailed: "备份操作失败，请检查文件后重试。",
    recentRecalls: "最近召回",
    setupTitle: "选择语言",
    setupDescription: "选择工作台使用的语言，之后可在设置中修改。",
    continue: "继续",
    savedNote: "已保存",
    savedCount: "已保存",
    openMenu: "打开菜单",
    toggleLight: "切换浅色模式",
    toggleDark: "切换深色模式",
    storageNote: "记忆仅保存在当前设备。",
    savedMemories: "已保存",
    countMemories: "条记忆",
    recallTimes: "次召回",
    mcpKicker: "Agent 集成",
    mcpTitle: "连接你的 Agent",
    mcpDescription:
      "Memory One 通过 Streamable HTTP 提供记忆工具。创建一个按工具授权的 Key 后，把带 Authorization Header 的配置加入 MCP 客户端。",
    mcpOnline: "HTTP 在线",
    mcpEndpoint: "服务地址",
    mcpCopyEndpoint: "复制服务地址",
    transport: "传输方式",
    auth: "认证",
    noAuth: "必须使用 Bearer Key",
    category: "记忆分类",
    categoryValue: "全局 / 可选 scope",
    toolsLabel: "可用工具",
    toolsTitle: "Agent 可以使用的工具",
    toolsCount: "个工具",
    http: "HTTP",
    localMemory: "本地记忆 / 01",
    serverEndpoint: "服务端点",
    versionNotice: (latest: string, current: string) => `发现新版本 ${latest}，当前版本 ${current}`,
    callCount: "次",
    appearance: "界面显示",
    appearanceEyebrow: "界面显示",
    darkMode: "深色模式",
    darkModeDescription: "在浅色和深色界面之间切换。",
    storageEyebrow: "本地存储",
    agentName: "记忆管家",
    agentDescription: "基于记忆回答你的问题",
    collapse: "收起",
    agentPage: "Agent 页面",
    chat: "对话",
    backToChat: "返回对话",
    configuration: "配置",
    processing: "正在处理",
    readingMemory: "正在读取记忆并生成回复",
    agentPlaceholder: "向记忆管家提问...",
    send: "发送",
    requestFormat: "请求格式",
    chooseRequestFormat: "选择请求格式",
    model: "模型",
    chooseOrEnterModel: "选择或输入模型",
    fetchModels: "获取列表",
    saving: "保存中",
    saved: "已保存",
    saveConfiguration: "保存配置",
    configSaveFailed: "配置保存失败，请稍后重试。",
    missingBaseUrl: "请先填写 Base URL。",
    missingApiKey: "请先完成 Agent 配置。",
    providerRequestFailed: "模型供应商请求失败，请检查供应商、模型和 Base URL。",
    agentRequestFailed: "暂时无法连接记忆管家，请稍后再试。",
    fetchedModels: (count: number) => `已获取 ${count} 个模型`,
    noModels: "没有可用模型",
    modelListFailed: "模型列表获取失败，请检查配置。",
    welcome: "你好，我是记忆管家。可以帮你搜索、保存、修改、删除记忆，也可以总结你的偏好和特点。",
    suggestionTraits: "总结我的特点",
    suggestionProjects: "搜索最近的项目约定",
    suggestionConcise: "记住我喜欢简洁的界面",
    openAgent: "打开记忆管家",
    agentTabs: "Agent 页面",
  },
  en: {
    brandSubtitle: "Personal memory", workspace: "Workspace", collections: "Collections", connect: "Connect",
    navAll: "All memories", navTimeline: "Timeline", navPreferences: "Preferences", navScopes: "Scopes", navTags: "Tags", navMcp: "MCP service", navSettings: "Settings",
    localStorage: "Local storage", memories: "MEMORIES", scopes: "SCOPES", scopesNote: "Scope count", lastSync: "LAST SYNC", justNow: "Just now", localDatabase: "Local database", localOnly: "Local only", localOnlyDesc: "Your memories stay on this device", newMemory: "New memory", search: "Search memories...", allScopes: "All scopes", reading: "Loading...", countSuffix: " memories", sortRecent: "Sorted by recently updated", sortTimeline: "Sorted by event time", sortGrouped: "Grouped by scope", globalMemory: "Global memories", emptyMatch: "No matching memories", emptyHelp: "Try another search or adjust the filters.", loadFailed: "Could not load memories", retry: "Retry", noTags: "No tags", settingsManaged: "Managed by local settings", detailEyebrow: "Memory details", close: "Close", detailEmpty: "Select a memory", detailEmptyDesc: "View its content and metadata", confidence: "Confidence", created: "Created", updated: "Updated", source: "Source", agentWritten: "Agent", scope: "Scope", signals: "Signals", importance: "Importance", recallCount: "Recalls", times: "times", original: "View original", switchLanguage: "Switch to Chinese", languageCode: "中", timelineItems: "items",
    languageName: "English", languageTitle: "Interface language", languageDescription: "Choose the language used by the workspace.", languageZh: "中文", languageEn: "English", languageSaved: "Language updated", languageSaveFailed: "Could not update language. Try again.", setupTitle: "Choose a language", setupDescription: "Choose a language for the workspace. You can change it later in Settings.", continue: "Continue", savedNote: "Saved", savedCount: "Saved", openMenu: "Open menu", toggleLight: "Switch to light mode", toggleDark: "Switch to dark mode", storageNote: "Memories stay on this device.", savedMemories: "Saved", countMemories: " memories", recallTimes: " recalls", backupEyebrow: "DATA BACKUP", backupTitle: "Export and import", backupDescription: "Export memories and safe configuration, or restore from a JSON backup. Replace mode overwrites current memories.", exportBackup: "Export JSON", importMerge: "Merge import", importReplace: "Replace import", replaceConfirm: "Replace import deletes all current memories and substitutes the backup. Continue?", backupImported: (imported: number, skipped: number) => `Imported ${imported} memories; skipped ${skipped}.`, backupFailed: "Backup operation failed. Check the file and try again.", recentRecalls: "Recent recalls",
    newMemoryEyebrow: "New memory", composerTitle: "Save a memory", content: "Memory", contentPlaceholder: "For example: The user prefers a concise interface.", type: "Type", scopeOptional: "Optional, for example: /path/to/project", sourcePlaceholder: "For example: Claude Code / Manual", writeLocal: "Save locally", preferenceRecall: "Recall mode", persistentPreference: "Persistent preference", conditionalPreference: "Conditional preference", persistentPreferenceHint: "Always returned at the start of every task", cancel: "Cancel", save: "Save memory", mcpKicker: "Agent integration", mcpTitle: "Connect your agent", mcpDescription: "Expose Memory One through Streamable HTTP. Create a scoped key and add it to your MCP client.", mcpOnline: "HTTP online", mcpEndpoint: "Service address", mcpCopyEndpoint: "Copy service address", transport: "Transport", auth: "Authentication", noAuth: "Bearer Key required", category: "Memory scope", categoryValue: "Global / optional scope", toolsLabel: "Available tools", toolsTitle: "Tools available to agents", toolsCount: "tools", http: "HTTP", localMemory: "LOCAL MEMORY / 01", serverEndpoint: "Service endpoint", versionNotice: (latest: string, current: string) => `New version ${latest}; current version ${current}`, callCount: "calls",
    appearance: "Appearance",
    appearanceEyebrow: "APPEARANCE",
    darkMode: "Dark mode",
    darkModeDescription: "Switch between light and dark themes.",
    storageEyebrow: "STORAGE",
    agentName: "Memory assistant",
    agentDescription: "Answer questions using your memories",
    collapse: "Collapse",
    agentPage: "Agent page",
    chat: "Chat",
    backToChat: "Back to chat",
    configuration: "Configuration",
    processing: "Processing",
    readingMemory: "Reading memories and preparing a reply",
    agentPlaceholder: "Ask the memory assistant a question...",
    send: "Send",
    requestFormat: "Request format",
    chooseRequestFormat: "Choose a request format",
    model: "Model",
    chooseOrEnterModel: "Choose or enter a model",
    fetchModels: "Fetch models",
    saving: "Saving",
    saved: "Saved",
    saveConfiguration: "Save configuration",
    configSaveFailed: "Could not save the configuration. Try again.",
    missingBaseUrl: "Enter a Base URL first.",
    missingApiKey: "Complete the agent configuration first.",
    providerRequestFailed: "The model provider request failed. Check the provider, model, and Base URL.",
    agentRequestFailed: "Could not connect to the memory assistant. Try again.",
    fetchedModels: (count: number) => `${count} models found`,
    noModels: "No models available",
    modelListFailed: "Could not fetch models. Check the configuration.",
    welcome: "Hi, I’m the memory assistant. I can search, save, update, and delete memories, or summarize your preferences.",
    suggestionTraits: "Summarize my preferences",
    suggestionProjects: "Search recent project conventions",
    suggestionConcise: "Remember that I prefer concise interfaces",
    openAgent: "Open memory assistant",
    agentTabs: "Agent page",
  },
} as const;
